---
title: "Schroedinger's Emission Trading System"
description: |
  The cat isn't a cat.
author:
  - name: Ralf Martin
    url: https://mondpanther.github.io/wwwmondpanther/
date: 03-03-2021
output:
  distill::distill_article:
    self_contained: false
categories:
  - ETS
  - Climate Change
  - Carbon Leakage
preview: etsplant.png    
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

The European Emissions Trading System (EU ETS) is often accused of two mutually exclusive concerns: On the one hand people complain that it endangers the competitiveness of regulated European companies who are competing with companies in un-regulated  places abroad. On the other hand, people complain that the permit prices are too low to incentivise any meaningful emission reduction. 
While both cannot be right, they can actually both be wrong, which is a conclusion supported by our latest research, namely: the ETS has led to meaningful emission reductions but did so largely without affecting the competitiveness of regulated firms.

We find this using French firm level manufacturing data [here](https://cep.lse.ac.uk/_NEW/PUBLICATIONS/abstract.asp?index=7591). ETS regulated manufacturing firms have reduced emissions by 10% more than comparable non regulated firms. In addition we find that investment (in particular in efficiency improving investment) in those firms increased and output did not decline. Neither is there evidence that they outsourced carbon intensive production steps. This suggests that their competitiveness did not suffer and carbon did not "leak".

