---
title: "Clean Innovation"
description: |
  Many lagging countries have a comparative advantage in clean innovation
author:
  - name: Ralf Martin
    url: https://mondpanther.github.io/wwwmondpanther/
date: 03-03-2021
output:
  distill::distill_article:
    self_contained: false
categories:
  - Innovation
  - Climate Change
  - Development
preview: 'rs.png'
    
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


Which countries have a comparative advantage in clean technologies? The Figure below examines this by looking at the share of clean innovations in total innovation across countries (using PATSTAT patent data.). A surprising number of developing countries have a comparative advantage in clean teachnologies.



```{r read data ,include=FALSE}
library(dplyr)


library(dbplyr)
library(dplyr)

library(readr)
library(lubridate)

library(readr)
#nuts3dat=read.csv("nuts3dat.csv")
```




```{r,include=FALSE,echo=FALSE}
library(dplyr)

rta=read.csv("https://www.dropbox.com/s/3qyeyrq1a9g0nix/rta.csv?dl=1")





```



```{r scatter,echo=FALSE,eval=FALSE, include=FALSE}
library(ggplot2)
ggplot(rta,aes(x=all,y=cleanshw))+geom_point()+geom_smooth(method = "lm", se = T ) + theme_minimal()


ggplot(rta,aes(x=log(1+all),y=cleanshw))+geom_point()+geom_smooth(method = "lm", se = T ) + theme_minimal()

ggplot(rta,aes(x=log(all),y=cleansh))+geom_point()+geom_smooth(method = "lm", se = T ) + theme_minimal()


lm(cleanshw~log(1+all),rta %>% filter(all>20)) %>%  summary()
lm(cleanshw~all,rta %>% filter(all>20)) %>%  summary()

```

```{r prepare globe,include=FALSE}


library(plotly)
df <- read.csv('https://raw.githubusercontent.com/plotly/datasets/master/2014_world_gdp_with_codes.csv')
df[,2] <- as.numeric(df[,2])
df[,2] <- log(df[,2])


clook=read.csv("https://www.dropbox.com/s/3hb2kol78zgb4h0/ccodelook.csv?dl=1")

df=df %>% left_join(clook,by=c("CODE"="ccode3")) %>% left_join(rta %>% filter(all>0),by="ccode") 
# appearance

#Set country boundaries as light grey
l <- list(color = toRGB("#d1d1d1"), width = 0.5)
#Specify map projection and options
g <- list(
     showframe = FALSE,
     showcoastlines = FALSE,
     projection = list(type = 'orthographic'),
     resolution = '100',
     showcountries = TRUE,
     countrycolor = '#d1d1d1',
     showocean = TRUE,
     oceancolor = '#c9d2e0',
     showlakes = TRUE,
     lakecolor = '#99c0db',
     showrivers = TRUE,
     rivercolor = '#99c0db')

df=df %>% mutate(toplot=(cleanshw/( sum(allclean,na.rm=T)/sum(all,na.rm=T)*100)-1)*100)
df=df %>% mutate(toplot=cleanshw)




drsimonj_colors <- c(
  `red`        = "#d11141",
  `green`      = "#00b159",
  `blue`       = "#00aedb",
  `orange`     = "#f37735",
  `yellow`     = "#ffc425",
  `light grey` = "#cccccc",
  `dark grey`  = "#8c8c8c")
drsimonj_cols <- function(...) {
  cols <- c(...)

  if (is.null(cols))
    return (drsimonj_colors)

  drsimonj_colors[cols]
}

drsimonj_palettes <- list(
  `main`  = drsimonj_cols("blue", "green", "yellow"),

  `cool`  = drsimonj_cols("blue", "green"),

  `hot`   = drsimonj_cols("yellow", "orange", "red"),

  `mixed` = drsimonj_cols("blue", "green", "yellow", "orange", "red"),

  `grey`  = drsimonj_cols("light grey", "dark grey")
)
drsimonj_pal <- function(palette = "main", reverse = FALSE, ...) {
  pal <- drsimonj_palettes[[palette]]

  if (reverse) pal <- rev(pal)

  colorRampPalette(pal, ...)
}


spet=drsimonj_pal("cool")(20)

#library(inlmisc)
#spet=inlmisc::GetTolColors(34, blind = "tritan")
library(jcolors)

spet=jcolors('pal11')
```


```{r globeprep,  fig.cap="Share of clean in total innovation",include=FALSE,message=FALSE,echo=FALSE}
#library(dichromat)
library(shiny)

p <- plot_geo(df) %>%
     add_trace(z = ~toplot, color = ~(toplot), colors = spet,
     text = ~COUNTRY, locations = ~CODE, marker = list(line = l)) %>%
     colorbar(title = 'Share of Cleantech Innovaion in %') %>%
     layout(title = '', geo = g)
```


```{r,include=FALSE}
library(knitr)
knit_hooks$set(customcap= function(before, options, envir) {
  if(!before) {
    paste('<p class="caption"> (\\#fig:globe)',options$customcap,"</p>",sep="")
    }
    })
```
 

```{r globe,  customcap="Share of clean in total innovation (in %)",echo=FALSE}

div(p)

```

